### ISSUE TITLE
Odd startup crash with 1710.1.4.1.43

### ISSUE THREAD

**Issue by DarVillous** [bdew-minecraft/gendustry#66]
Everything works with 1.4.0.41 but when I swap to 1.4.1.43 it crashes (the report is below).

In both cases the are using the following version of the mods
bdlib-mc170-1.5.1.32
forestry 3.1.1.4
forge 10.13.2.1235

Any thoughts?

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 11/8/14 10:26 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/bdew/gendustry/compat/triggers/TriggerProvider$
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoClassDefFoundError: net/bdew/gendustry/compat/triggers/TriggerProvider$
    at net.bdew.gendustry.Gendustry$.preInit(Gendustry.scala:65)
    at net.bdew.gendustry.Gendustry.preInit(Gendustry.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    ... 18 more
Caused by: java.lang.ClassNotFoundException: net.bdew.gendustry.compat.triggers.TriggerProvider$
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 46 more
Caused by: java.lang.NoClassDefFoundError: buildcraft/api/statements/ITriggerProvider
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 48 more
Caused by: java.lang.ClassNotFoundException: buildcraft.api.statements.ITriggerProvider
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 52 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 597501888 bytes (569 MB) / 1796734976 bytes (1713 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx4096m -XX:PermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1235 Minecraft Forge 10.13.2.1235 93 mods loaded, 93 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.85.1235} [Forge Mod Loader](forge-1.7.10-10.13.2.1235-universal.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.2.1235} [Minecraft Forge](forge-1.7.10-10.13.2.1235-universal.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized
    MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks](minecraft.jar) Unloaded->Constructed->Pre-initialized
    MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.3.67} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.67-universal.jar) Unloaded->Constructed->Pre-initialized
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    Baubles{1.0.1.8} [Baubles](Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed->Pre-initialized
    Thaumcraft{4.2.1.4} [Thaumcraft](Thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed->Pre-initialized
    arsmagica2{1.4.0.005} [Ars Magica 2](1.7.10_AM2_1.4.0.005.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2{rv1-stable-1} [Applied Energistics 2](appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized
    bdlib{1.5.1.32} [BD Lib](bdlib-mc1710-1.5.1.32.jar) Unloaded->Constructed->Pre-initialized
    BiblioCraft{1.8.2} [BiblioCraft](BiblioCraft[v1.8.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
    CoFHCore{1.7.10R3.0.0B7} [CoFH Core](CoFHCore-[1.7.10]3.0.0B7-35.jar) Unloaded->Constructed->Pre-initialized
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized
    ThermalExpansion{1.7.10R4.0.0B6} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B6-16.jar) Unloaded->Constructed->Pre-initialized
    BigReactors{0.4.0rc11} [Big Reactors](BigReactors-0.4.0rc11.jar) Unloaded->Constructed->Pre-initialized
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1004-universal.jar) Unloaded->Constructed->Pre-initialized
    AWWayofTime{v1.2.0b} [Blood Magic: Alchemical Wizardry](Blood Magic-v1.2.0b%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized
    CarpentersBlocks{3.3.0} [Carpenter's Blocks](Carpenter's Blocks v3.3.0 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized
    cookiecore{1.3.0} [Cookie Core](cookiecore-1.3.0.jar) Unloaded->Constructed->Pre-initialized
    Enchiridion{1.1} [Enchiridion](Enchiridion-1.7.X-1.2b.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded{1.7.10R2.8.0RC4} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    Forestry{3.1.1.4} [Forestry for Minecraft](forestry_1.7.10-3.1.1.4.jar) Unloaded->Constructed->Pre-initialized
    Railcraft{9.3.3.0} [Railcraft](Railcraft_1.7.10-9.3.3.0.jar) Unloaded->Constructed->Pre-initialized
    EnderIO{1.7.10-2.1.8.260} [Ender IO](EnderIO-1.7.10-2.1.8.260.jar) Unloaded->Constructed->Pre-initialized
    EnderStorage{1.4.5.25} [EnderStorage](EnderStorage-1.7.10-1.4.5.25-universal.jar) Unloaded->Constructed->Pre-initialized
    enhancedportals{3.0.7} [EnhancedPortals](EnhancedPortals_1.7.10-universal-3.0.7.jar) Unloaded->Constructed->Pre-initialized
    Waila{1.5.5} [Waila](Waila-1.5.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    extracells{2.1.12} [ExtraCells](ExtraCells-1.7.10-2.1.12bnull.jar) Unloaded->Constructed->Pre-initialized
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
    TConstruct{1.7.10-1.7.1.build771} [Tinkers' Construct](TConstruct-1.7.10-1.7.1c.jar) Unloaded->Constructed->Pre-initialized
    ExtraTiC{0.8.4} [ExtraTiC](ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized
    ForgeMultipart{1.1.0.313} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.313-universal.jar) Unloaded->Constructed->Pre-initialized
    ExtraUtilities{1.1.0k} [Extra Utilities](extrautilities-1.1.0k.jar) Unloaded->Constructed->Pre-initialized
    fastleafdecay{1.0} [Fast Leaf Decay](FastLeafDecay-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized
    FlatSigns{2.1.0.19} [Flat Signs](FlatSigns-1.7.10-universal-2.1.0.19.jar) Unloaded->Constructed->Pre-initialized
    McMultipart{1.1.0.313} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.313-universal.jar) Unloaded->Constructed->Pre-initialized
    ganysnether{1.7.5} [Gany's Nether](Ganys Nether-1.7.5.jar) Unloaded->Constructed->Pre-initialized
    ThaumicTinkerer{2.5-1.7.10-158} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-158.jar) Unloaded->Constructed->Pre-initialized
    MagicBees{1.7.10-2.1.22} [Magic Bees](magicbees-1.7.10-2.1.22.jar) Unloaded->Constructed->Pre-initialized
    gendustry{1.4.1.43} [GenDustry](gendustry-mc1710-1.4.1.43.jar) Unloaded->Constructed->Errored
    iChunUtil{4.0.0} [iChunUtil](iChunUtil-4.0.0.jar) Unloaded->Constructed->Pre-initialized
    Hats{4.0.1} [Hats](Hats-4.0.1.jar) Unloaded->Constructed->Pre-initialized
    HatStand{4.0.0} [HatStand](HatStand-4.0.0.jar) Unloaded->Constructed->Pre-initialized
    inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks](InventoryTweaks-1.59-dev-156.jar) Unloaded->Constructed->Pre-initialized
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops](magicalcrops-1.7.10_0.1.jar) Unloaded->Constructed->Pre-initialized
    Mariculture{1.2.3d} [Mariculture](Mariculture-1.7.10-1.2.3d.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC4} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC3} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC4} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC4} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC3} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC3} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC4} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC3} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC3} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC3} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC3} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC3} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC3} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC3} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC4} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC3} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    TwilightForest{2.3.2} [The Twilight Forest](twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC4} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC4} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    Morph{0.9.1} [Morph](Morph-Beta-0.9.1.jar) Unloaded->Constructed->Pre-initialized
    Morpheus{1.7.10-1.5.24} [Morpheus](Morpheus-1.7.10-1.5.24.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons{1.12.3.11} [NEI Addons](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    ObsidiPlates{3.0.0.18} [ObsidiPlates](ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded->Constructed->Pre-initialized
    MapWriter{2.1.1} [MapWriter](Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Opis{1.2.3} [Opis](Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    harvestcraft{1.7.10b} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10c.jar) Unloaded->Constructed->Pre-initialized
    PneumaticCraft{1.3.1-31} [PneumaticCraft](PneumaticCraft-1.7.10-1.3.1-31-universal.jar) Unloaded->Constructed->Pre-initialized
    rancraftpenguins{1.7.10q} [Rancraft Penguins](rancraftpenguins-1.7.10q.jar) Unloaded->Constructed->Pre-initialized
    Roguelike{1.3.5} [Roguelike Dungeons](roguelike-1.7.10-1.3.5.jar) Unloaded->Constructed->Pre-initialized
    thaumicenergistics{0.7.3b} [Thaumic Energistics](thaumicenergistics-0.7.3b.jar) Unloaded->Constructed->Pre-initialized
    TSteelworks{1.7.10-1.0.6} [Tinkers' Steelworks](TSteelworks-1.7.10-1.0.6.jar) Unloaded->Constructed->Pre-initialized
    TiCTooltips{1.1.11b} [TiC Tooltips](TiCTooltips-mc1.7.10-1.1.11b.jar) Unloaded->Constructed->Pre-initialized
    TMechworks{1.7.10-86.e500b88} [Tinkers' Mechworks](TMechworks-1.7.10-0.2.10.jar) Unloaded->Constructed->Pre-initialized
    WailaHarvestability{1.1.0} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.0.jar) Unloaded->Constructed->Pre-initialized
    witchery{0.20.6} [Witchery](witchery-1.7.10-0.20.6.jar) Unloaded->Constructed->Pre-initialized
    ForgeMicroblock{1.1.0.313} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.313-universal.jar) Unloaded->Constructed->Pre-initialized
    IguanaTweaksTConstruct{1.7.10-2.0.6} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.0.6.jar) Unloaded->Constructed->Pre-initialized
    AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.

**Comment by bdew** [comment]
Gendustry 1.4.1 requires BuildCraft 6.1 API, which you don't have.

Either update to forestry unstable versions (which has it included), or install BuildCraft 6.1.x
